<div id="comments">
<?php echo $this->form ?>
<?php if (!empty($this->comments)):?>
	<ul>
	<?php foreach ($this->comments as $comment):?>
		<li>
			<dl>
				<dt><em><?php echo $comment['POST_AUTHOR']?></em>&nbsp;|&nbsp;<?php echo $comment['POST_POSTDATE']?></dt>
				<dd><?php echo $comment['POST_POST']?></dd>
			</dl>
		</li>
	<?php endforeach;?>
	</ul>
<?php endif;?>
</div>
<script type="text/javascript">
	$("input:submit, input:button, button").button();
	$("#commentForm").submit(function() {
		$.post(
			$(this).attr("action"),
			$(this).serialize(),
			function(data) {
				$.get(
						'/catalog/products/comments/product/<?php echo $this->product->getAlias();?>/format/html', 
						function(data) {
							$("#comments").empty();
					  		$('#comments').html(data);
						}
				);
			}
		);
		return false;
	});

</script>
