<table id="list" class="scroll"></table>
<div id="pager" class="scroll" style="text-align:center;"></div>

<script type="text/javascript">
jQuery('#list').jqGrid({
	url:'/catalog/prices/list/format/json',
	datatype: 'json',
	mtype: 'GET',
	colNames:['Id', 'Product', 'Cost', 'Currency', 'Created', 'Actual To', 'Author'],
	colModel :[
	  {name:'PRICE_ID', index:'POST_ID', sorttype:'int', width:50},
	  {name:'PRICE_PRODUCTID', index:'PRICE_PRODUCTID', editable:true, editrules:{required:true}, edittype:'select', editoptions:{value:{<?php foreach ($this->prods as $id => $title) echo "{$id}:'{$title}',"; ?>}}},
	  {name:'PRICE_COST', index:'PRICE_COST', editable:true},
	  {name:'PRICE_CURRENCYID', index:'PRICE_CURRENCYID', editable:false},
	  {name:'PRICE_CREATEDATE', index:'PRICE_CREATEDATE', editable:false},
	  {name:'PRICE_ACTUALTO', index:'PRICE_ACTUALTO', editable:false},
	  {name:'PRICE_AUTHOR', index:'POST_AUTHOR', editable:false}
	],
	pager: jQuery('#pager'),
	rowNum:20,
	rowList:[20, 40, 60, 80, 100, 150, 200],
	sortname: 'PRICE_ID',
	sortorder: 'asc',
	viewrecords: true,
	caption: 'Prices View',
	editurl: '/catalog/prices/edit',
	height:'auto',
	width:'auto'
}).navGrid('#pager',{
	edit:true, add:true, del:true, search:true
});
</script>
