<?php $elements = $this->form->getElements();?>
<?php if (count($elements) > 1):?>
<h4 class="hx-style01"><span>Фильтр</span></h4>
<div class="box" id="filterbox">
	<form action="<?php echo $this->form->getAction();?>" method="<?php $this->form->getMethod();?>" enctype="<?php $this->form->getEncType();?>">
		<div class="box">
		<?php foreach ($elements as $element):?>
			<?php $pos++;?>
			<?php if ($element->getName() != 'submit'):?>
				<div class="col30<?php if (($pos + 1) % 3 == 0):?> margin<?php elseif ($pos % 3 == 0):?> fix<?php endif;?>"><?php echo $element->render();?></div>
				<?php if ($pos % 3 != 0):?><hr class="noscreen" /><?php endif;?>
			<?php endif;?>
	<?php echo Zend_Registry::get('logger')->err($pos);?>
		<?php endforeach;?>
		</div>
		<div class="box t-center"><?php echo $this->form->getElement('submit')->setLabel('Фильтровать')->render();?></div>
	</form>
</div>
<hr class="noscreen" />
<?php endif;?>

<?php //Zend_Registry::get('logger')->err($this->paginator->getCurrentItems());?>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
<div class="box">
<?php $products = $this->paginator->getCurrentItems();?>
<?php $prodsCount = count($products);?>
<?php if ($prodsCount):?>
    <?php for ($pos = 1; $pos <= $prodsCount; $pos++):?>
    <?php $product = $products[$pos - 1];?>
    <?php array_push($this->keywords, $product['BRANDS_TITLE'] . ' ' . $product['PRODUCTS_TITLE'], $product['CATEGORIES_TITLE']);?>
    <div class="col30<?php if (($pos + 1) % 3 == 0):?> margin<?php elseif ($pos % 3 == 0):?> fix<?php endif;?>">
        <h4><a href="<?php echo $this->url(array('module' => 'catalog', 'controller' => 'products', 'action' => 'view'), null, true); ?>/product/<?php echo $product['PRODUCTS_ALIAS'];?>"><?php echo $product['BRANDS_TITLE'] . ' ' . $product['PRODUCTS_TITLE'];?></a></h4>
        <p class="date">
            <?php echo date("d-m-Y", strtotime($product['PRODUCTS_DATE']));?> &nbsp;&ndash;&nbsp;
            <a href="<?php echo $this->url(array('module' => 'catalog', 'controller' => 'categories', 'action' => 'list'), null, true); ?>/category/<?php echo $product['CATEGORIES_ALIAS'];?>"><?php echo $product['CATEGORIES_TITLE'];?></a>
        </p>
        <p class="bb box" style="height:95px;"><img src="<?php if (!empty($product['PHOTOS_FILE'])):?>/timthumb/timthumb.php?src=<?php echo $product['PHOTOS_FILE'];?>&h=75&w=100&zc=0<?php else:?>/images/image-03.gif<?php endif;?>" width="100" height="75" alt="" class="f-left" /><?php echo mb_substr($product['PRODUCTS_SHORTDESCR'], 0, 90, 'utf-8');?>...</p>
        <p class="t-center"><a href="<?php echo $this->url(array('module' => 'catalog', 'controller' => 'products', 'action' => 'view'), null, true); ?>/product/<?php echo $product['PRODUCTS_ALIAS'];?>" class="ico-more">Подробнее...</a></p>
    </div>
    <?php if ($pos % 3 != 0):?><hr class="noscreen" /><?php endif;?>
    <?php endfor;?>
<?php endif;?>
</div>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>

<hr class="noscreen" />
