<?php if ($this->pageCount): ?>
    <div class="paginationControl">
    <!-- Previous page link -->
    <?php if (isset($this->previous)): ?>
        <a href="<?php echo $this->url(array('page' => $this->previous)); ?>?<?php echo $_SERVER['QUERY_STRING'];?>">
          &lt; Предыдущая
        </a> |
    <?php else: ?>
        <span class="disabled">&lt; Предыдущая</span> |
    <?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <a href="<?php echo $this->url(array('page' => $page)); ?>?<?php echo $_SERVER['QUERY_STRING'];?>"><?php echo $page; ?></a> |
  <?php else: ?>
    <span class="active"><?php echo $page; ?></span> |
  <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <a href="<?php echo $this->url(array('page' => $this->next)); ?>?<?php echo $_SERVER['QUERY_STRING'];?>">Следующая &gt;</a>
<?php else: ?>
  <span class="disabled">Следующая &gt;</span>
<?php endif; ?>
</div>
<?php endif; ?>
