-- 28-10-2009
CREATE TABLE `MIXMARKET_LINKCATEGORIES` (
  `LINKCATEGORIES_CATALOGID` int(10) unsigned NOT NULL,
  `LINKCATEGORIES_MIXID` int(10) unsigned NOT NULL,
  KEY `LINKCATEGORIES_CATALOGID` (`LINKCATEGORIES_CATALOGID`),
  KEY `LINKCATEGORIES_MIXID` (`LINKCATEGORIES_MIXID`),
  CONSTRAINT `MIXMARKET_LINKCATEGORIES_ibfk_2` FOREIGN KEY (`LINKCATEGORIES_MIXID`) REFERENCES `MIXMARKET_CATEGORIES` (`CATEGORIES_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `MIXMARKET_LINKCATEGORIES_ibfk_1` FOREIGN KEY (`LINKCATEGORIES_CATALOGID`) REFERENCES `CATALOG_CATEGORIES` (`CATEGORIES_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MIXMARKET_LINKBRANDS` (
  `LINKBRANDS_CATALOGID` int(10) unsigned NOT NULL,
  `LINKBRANDS_MIXID` int(10) unsigned NOT NULL,
  KEY `LINKBRANDS_CATALOGID` (`LINKBRANDS_CATALOGID`),
  KEY `LINKBRANDS_MIXID` (`LINKBRANDS_MIXID`),
  CONSTRAINT `MIXMARKET_LINKBRANDS_ibfk_2` FOREIGN KEY (`LINKBRANDS_MIXID`) REFERENCES `MIXMARKET_BRANDS` (`BRANDS_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `MIXMARKET_LINKBRANDS_ibfk_1` FOREIGN KEY (`LINKBRANDS_CATALOGID`) REFERENCES `CATALOG_BRANDS` (`BRANDS_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MIXMARKET_LINKOFFERS` (
  `LINKOFFERS_CATALOGID` int(10) unsigned NOT NULL,
  `LINKOFFERS_MIXID` int(10) unsigned NOT NULL,
  KEY `LINKOFFERS_CATALOGID` (`LINKOFFERS_CATALOGID`),
  KEY `LINKOFFERS_MIXID` (`LINKOFFERS_MIXID`),
  CONSTRAINT `MIXMARKET_LINKOFFERS_ibfk_1` FOREIGN KEY (`LINKOFFERS_CATALOGID`) REFERENCES `CATALOG_PRODUCTS` (`PRODUCTS_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `MIXMARKET_LINKOFFERS_ibfk_2` FOREIGN KEY (`LINKOFFERS_MIXID`) REFERENCES `MIXMARKET_OFFERS` (`OFFERS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8


