<table id="list" class="scroll"></table>
<div id="pager" class="scroll" style="text-align:center;"></div>

<script type="text/javascript">
jQuery('#list').jqGrid({
	url:'/catalog/currencies/list/format/json',
	datatype: 'json',
	mtype: 'GET',
	colNames:['Id', 'Title', 'Reduction'],
	colModel :[
	  {name:'CURRENCY_ID', index:'CURRENCY_ID', sorttype:'int', width:50},
	  {name:'CURRENCY_TITLE', index:'CURRENCY_TITLE', editable:true},
	  {name:'CURRENCY_REDUCTION', index:'CURRENCY_REDUCTION', editable:true}
	],
	pager: jQuery('#pager'),
	rowNum:20,
	rowList:[20, 40, 60, 80, 100, 150, 200],
	sortname: 'CURRENCY_ID',
	sortorder: 'asc',
	viewrecords: true,
	caption: 'Currencies View',
	editurl: '/catalog/currencies/edit',
	height:'auto',
	width:'auto'
}).navGrid('#pager',{
	edit:true, add:true, del:true, search:true
});
</script>
