        <h4 class="hx-style01"><span>Photos</span></h4>
        <div id="photos" class="box">
            <a href="#"><img src="/images/image-02.gif" alt="" class="nom" /></a>
            <a href="#"><img src="/images/image-02.gif" alt="" /></a>
            <a href="#"><img src="/images/image-02.gif" alt="" /></a>
            <a href="#"><img src="/images/image-02.gif" alt="" /></a>
            <a href="#"><img src="/images/image-02.gif" alt="" /></a>
            <a href="#"><img src="/images/image-02.gif" alt="" /></a>
        </div> <!-- /photos -->
<?php Zend_Registry::get('logger')->err($this->popular);?>
        <!-- Best informations -->
        <h4 class="hx-style01"><span>Самые популярные</span></h4>
        <div class="box">
            <?php for ($pos = 1; $pos <= count($this->popular); $pos++):?>
            <?php $product = $this->popular[$pos - 1];?>
            <!-- Column I -->
            <div class="col30<?php if (($pos + 1) % 3 == 0):?> margin<?php elseif (($pos + 1) % 3 == 0):?> fix<?php endif;?>">
                <h4><a href="<?php echo $this->url(array('module' => 'catalog', 'controller' => 'products', 'action' => 'view'), null, true); ?>/product/<?php echo $product->PRODUCTS_ALIAS;?>"><?php echo $product->BRANDS_TITLE . ' ' . $product->PRODUCTS_TITLE;?></a></h4>
                <p class="date">
                    <?php echo date("d-m-Y", strtotime($product->PRODUCTS_DATE));?> &nbsp;&ndash;&nbsp;
                    <a href="<?php echo $this->url(array('module' => 'catalog', 'controller' => 'categories', 'action' => 'list'), null, true); ?>/category/<?php echo $product->CATEGORIES_ALIAS;?>"><?php echo $product->CATEGORIES_TITLE;?></a> &nbsp;&ndash;&nbsp;
                    <a href="#">18 comments</a>
                </p>
                <p class="bb box" style="height:95px;"><img src="/images/image-03.gif" width="100" height="75" alt="" class="f-left" /><?php echo mb_substr($product->PRODUCTS_SHORTDESCR, 0, 90, 'utf-8');?>...</p>
                <p class="t-center"><a href="<?php echo $this->url(array('module' => 'catalog', 'controller' => 'products', 'action' => 'view'), null, true); ?>/product/<?php echo $product->PRODUCTS_ALIAS;?>" class="ico-more">Подробнее...</a></p>
            </div> <!-- /col30 -->
                <?php if ($pos % 3 != 0):?><hr class="noscreen" /><?php endif;?>
            <?php endfor;?>
        </div> <!-- /box -->

            <hr class="noscreen" />

        <!-- New informations -->
        <h4 class="hx-style01"><span>Последние добавления</span></h4>
        <div class="box">
            <?php for ($pos = 1; $pos <= count($this->newest); $pos++):?>
            <?php $product = $this->popular[$pos - 1];?>
            <!-- Column I -->
            <div class="col30<?php if (($pos + 1) % 3 == 0):?> margin<?php elseif (($pos + 1) % 3 == 0):?> fix<?php endif;?>">
                <h4><a href="<?php echo $this->url(array('module' => 'catalog', 'controller' => 'products', 'action' => 'view'), null, true); ?>/product/<?php echo $product->PRODUCTS_ALIAS;?>"><?php echo $product->BRANDS_TITLE . ' ' . $product->PRODUCTS_TITLE;?></a></h4>
                <p class="date">
                    <?php echo date("d-m-Y", strtotime($product->PRODUCTS_DATE));?> &nbsp;&ndash;&nbsp;
                    <a href="<?php echo $this->url(array('module' => 'catalog', 'controller' => 'categories', 'action' => 'list'), null, true); ?>/category/<?php echo $product->CATEGORIES_ALIAS;?>"><?php echo $product->CATEGORIES_TITLE;?></a> &nbsp;&ndash;&nbsp;
                    <a href="#">18 comments</a>
                </p>
                <p class="bb box" style="height:95px;"><img src="/images/image-03.gif" width="100" height="75" alt="" class="f-left" /><?php echo mb_substr($product->PRODUCTS_SHORTDESCR, 0, 90, 'utf-8');?>...</p>
                <p class="t-center"><a href="<?php echo $this->url(array('module' => 'catalog', 'controller' => 'products', 'action' => 'view'), null, true); ?>/product/<?php echo $product->PRODUCTS_ALIAS;?>" class="ico-more">Подробнее...</a></p>
            </div> <!-- /col30 -->
                <?php if ($pos % 3 != 0):?><hr class="noscreen" /><?php endif;?>
            <?php endfor;?>
        </div> <!-- /box -->
