    <h4 class="hx-style01"><span>Последние добавления</span></h4>
    <div class="box">
        <?php $cnt = count($this->newest);?>
        <?php for ($pos = 1; $pos <= $cnt; $pos++):?>
        <?php $product = $this->newest[$pos - 1];?>
        <div class="col30<?php if (($pos + 1) % 3 == 0):?> margin<?php elseif (($pos + 1) % 3 == 0):?> fix<?php endif;?>">
            <h4><a href="<?php echo $this->url(array('module' => 'catalog', 'controller' => 'products', 'action' => 'view'), null, true); ?>/product/<?php echo $product->PRODUCTS_ALIAS;?>" title="<?php echo $product->BRANDS_TITLE . ' ' . $product->PRODUCTS_TITLE;?>"><?php echo $product->BRANDS_TITLE . ' ' . $product->PRODUCTS_TITLE;?></a></h4>
            <p class="date">
                <?php echo date("d-m-Y", strtotime($product->PRODUCTS_DATE));?> &nbsp;&ndash;&nbsp;
                <a href="<?php echo $this->url(array('module' => 'catalog', 'controller' => 'categories', 'action' => 'list'), null, true); ?>/category/<?php echo $product->CATEGORIES_ALIAS;?>" title="<?php echo $product->CATEGORIES_TITLE;?>"><?php echo $product->CATEGORIES_TITLE;?></a>
            </p>
            <p class="bb box" style="height:95px;"><img src="<?php if (!empty($product->PHOTOS_FILE)):?>/timthumb/timthumb.php?src=<?php echo $product->PHOTOS_FILE;?>&h=75&w=100&zc=0<?php else:?>/images/image-03.gif<?php endif;?>" width="100" height="75" alt="<?php echo $product->BRANDS_TITLE . ' ' . $product->PRODUCTS_TITLE;?>" class="f-left" /><?php echo mb_substr($product->PRODUCTS_SHORTDESCR, 0, 90, 'utf-8');?>...</p>
            <p class="t-center"><a href="<?php echo $this->url(array('module' => 'catalog', 'controller' => 'products', 'action' => 'view'), null, true); ?>/product/<?php echo $product->PRODUCTS_ALIAS;?>" class="ico-more">Подробнее...</a></p>
        </div>
            <?php if ($pos % 3 != 0):?><hr class="noscreen" /><?php endif;?>
        <?php endfor;?>
    </div>

    <hr class="noscreen" />

    <h4 class="hx-style01"><span>Предложения партнеров</span></h4>
    <div class="box h-ads">
		<script type="text/javascript"><!--
		google_ad_client = "pub-1610147099732550";
		/* satdevice_horizontal_middle */
		google_ad_slot = "3281416997";
		google_ad_width = 728;
		google_ad_height = 90;
		//-->
		</script>
		<script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js"></script>
    </div>

    <hr class="noscreen" />

    <h4 class="hx-style01"><span>Самые популярные</span></h4>
    <div class="box">
        <?php $cnt = count($this->popular);?>
        <?php for ($pos = 1; $pos <= $cnt; $pos++):?>
        <?php $product = $this->popular[$pos - 1];?>
        <div class="col30<?php if (($pos + 1) % 3 == 0):?> margin<?php elseif (($pos + 1) % 3 == 0):?> fix<?php endif;?>">
            <h4><a href="<?php echo $this->url(array('module' => 'catalog', 'controller' => 'products', 'action' => 'view'), null, true); ?>/product/<?php echo $product->PRODUCTS_ALIAS;?>" title="<?php echo $product->BRANDS_TITLE . ' ' . $product->PRODUCTS_TITLE;?>"><?php echo $product->BRANDS_TITLE . ' ' . $product->PRODUCTS_TITLE;?></a></h4>
            <p class="date">
                <?php echo date("d-m-Y", strtotime($product->PRODUCTS_DATE));?> &nbsp;&ndash;&nbsp;
                <a href="<?php echo $this->url(array('module' => 'catalog', 'controller' => 'categories', 'action' => 'list'), null, true); ?>/category/<?php echo $product->CATEGORIES_ALIAS;?>"><?php echo $product->CATEGORIES_TITLE;?></a>
            </p>
            <p class="bb box" style="height:95px;"><img src="<?php if (!empty($product->PHOTOS_FILE)):?>/timthumb/timthumb.php?src=<?php echo $product->PHOTOS_FILE;?>&h=75&w=100&zc=0<?php else:?>/images/image-03.gif<?php endif;?>" width="100" height="75" alt="<?php echo $product->BRANDS_TITLE . ' ' . $product->PRODUCTS_TITLE;?>" class="f-left" /><?php echo mb_substr($product->PRODUCTS_SHORTDESCR, 0, 90, 'utf-8');?>...</p>
            <p class="t-center"><a href="<?php echo $this->url(array('module' => 'catalog', 'controller' => 'products', 'action' => 'view'), null, true); ?>/product/<?php echo $product->PRODUCTS_ALIAS;?>" class="ico-more">Подробнее...</a></p>
        </div>
            <?php if ($pos % 3 != 0):?><hr class="noscreen" /><?php endif;?>
        <?php endfor;?>
    </div>
