<table id="list" class="scroll"></table>
<div id="pager" class="scroll" style="text-align:center;"></div>

<script type="text/javascript">
jQuery('#list').jqGrid({
	url:'/catalog/brands/list/format/json',
	datatype: 'json',
	mtype: 'GET',
	colNames:['Id', 'Alias', 'Title', 'Url'],
	colModel :[
	  {name:'BRANDS_ID', index:'BRANDS_ID', sorttype:'int', width:50},
	  {name:'BRANDS_ALIAS', index:'BRANDS_ALIAS', editable:true, editrules:{required:true}},
	  {name:'BRANDS_TITLE', index:'BRANDS_TITLE', editable:true, editrules:{required:true}},
	  {name:'BRANDS_URL', index:'BRANDS_URL', editable:true, editrules:{required:true}}],
	pager: jQuery('#pager'),
	rowNum:20,
	rowList:[20, 40, 60, 80, 100, 150, 200],
	sortname: 'BRANDS_ID',
	sortorder: 'asc',
	viewrecords: true,
	caption: 'Brands View',
	editurl: '/catalog/brands/edit',
	height:'auto',
	width:'auto'
}).navGrid('#pager',{
	edit:true, add:true, del:true, search:true
});
</script>
