<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <meta http-equiv="content-language" content="en" />
  <meta name="robots" content="all,follow" />

  <meta name="author" lang="en" content="All: SatDevice [www.satdevice.com]; e-mail: support@satdevice.com" />
  <meta name="copyright" lang="en" content="KiT Studio" />

  <meta name="description" content="..." />
  <meta name="keywords" content="..." />

  <link href="/js/jquery/ui/18/css/ui-lightness/jquery-ui-1.8.custom.css" media="screen" rel="stylesheet" type="text/css" />
  <link rel="stylesheet" media="screen,projection" type="text/css" href="/css/main.css" />
  <!--[if lte IE 6]><link rel="stylesheet" type="text/css" href="/css/main-msie.css" /><![endif]-->
  <link rel="stylesheet" media="screen,projection" type="text/css" href="/css/scheme.css" />
  <link rel="stylesheet" media="print" type="text/css" href="/css/print.css" />

  <script type="text/javascript" src="/js/jquery/jquery-1.4.2.min.js"></script>
  <script type="text/javascript" src="/js/jquery/jquery.cookie.min.js"></script>
  <script type="text/javascript" src="/js/jquery/ui/18/jquery-ui-1.8.custom.min.js"></script>
  <script type="text/javascript" src="/js/custom.js"></script>
  <?php echo $this->headTitle(); ?>
</head>

<body>

<div id="main">
  <!-- Header -->
  <div id="header" class="box">
      <!-- Your logo -->
      <h1 id="logo"><a href="#" title="[Go to homepage]">SatDevice</a></h1>
      <!-- Your slogan -->
      <p id="slogan">Все для спутниквого телевидения</p>
      <hr class="noscreen" />
      <!-- Search -->
      <div id="search">
          <form action="" method="get">
              <div>
                  <span class="noscreen">Поиск:</span>
                  <input type="text" size="30" name="query" id="search-input" />
                  <input type="submit" value="Search" id="search-submit" />
              </div>
          </form>
      </div> <!-- /search -->
  </div> <!-- /header -->

  <hr class="noscreen" />
<?php //Zend_Registry::get('logger')->err($this->layout()->categories);?>
<?php //Zend_Registry::get('logger')->err($this->layout()->activeCategory);?>
  <!-- Navigation -->
  <div id="nav" class="box">
      <h3 class="noscreen">Разделы</h3>
      <ul>
          <li <?php if (!$this->layout()->activeCategory):?>id="nav-active"<?php endif;?>><a href="/">Главная</a></li>
      <?php foreach ($this->layout()->categories as $categoryAlias => $categoryTitle):?>
          <li <?php if ($this->layout()->activeCategory == $categoryAlias):?>id="nav-active"<?php endif;?>><a href="<?php echo $this->url(array('module' => 'catalog', 'controller' => 'categories', 'action' => 'list'), null, true); ?>/category/<?php echo $categoryAlias;?>"><?php echo $categoryTitle; ?></a></li>
      <?php endforeach;?>
          <li><a href="/contacts">Контакты</a></li>
      </ul>
  </div> <!-- /nav -->

  <hr class="noscreen" />

  <!-- Main content -->
  <div id="content" class="box">
    <?php echo $this->layout()->content ?>
  </div> <!-- /content -->

  <hr class="noscreen" />

  <!-- Footer -->
  <div id="footer">
      <p class="f-right"><a href="http://www.nuviotemplates.com/">Free web templates</a> presented by <a href="http://www.qartin.cz/">QARTIN</a>, vacation <a href="http://www.puntacana.net/">Punta Cana</a></p>
      <p>&copy;&nbsp;2010 <a href="/">SatDevice.com</a></p>
  </div> <!-- /footer -->

</div> <!-- /main -->

</body>
</html>
