<?php $categoryTitle = $this->category->getTitle();?>
<?php $this->description[] = $categoryTitle;?>
<?php array_push($this->keywords, 'купить', 'скачать драйвера', 'харакетристики', 'обзор');?>

		<div class="title01-top"></div>
		<div class="title01">
			<div class="title01-in">
				<h3 class="ico-info">
					<?php echo $categoryTitle;?>
				</h3>
			</div>
		</div>
		<div class="title01-bottom"></div>
		<p class="bb">
			<a href="/">Главная</a> &raquo;
			<?php if (!empty($this->parentCategory)):?>
			<?php $this->description[] = $this->parentCategory->getTitle();?>
				<?php $this->headTitle()->append($this->parentCategory->getTitle()); ?>
				<a href="<?php echo $this->url(array('module' => 'catalog', 'controller' => 'categories', 'action' => 'list'), null, true);?>/category/<?php echo $this->parentCategory->getAlias();?>"><?php echo $this->parentCategory->getTitle();?></a> &raquo;
			<?php endif;?>
			<strong><?php echo $categoryTitle;?></strong>
		</p>

<?php $this->headTitle()->append($categoryTitle); ?>
<?php if (!empty($this->childrenCategories)):?>
	<!-- Subcategories -->
	<h4>Подразделы:</h4>
	<ul class="ul-categories box">
	<?php foreach ($this->childrenCategories as $category):?>
		<?php $this->description[] = $category->CATEGORIES_TITLE;?>
		<?php $this->keywords[] = $category->CATEGORIES_TITLE;?>
		<li><a href="<?php echo $this->url(array('module' => 'catalog', 'controller' => 'categories', 'action' => 'list'), null, true);?>/category/<?php echo $category->CATEGORIES_ALIAS;?>"><?php echo $category->CATEGORIES_TITLE;?></a> (<?php echo isset($this->catsProdsCnt[$category->CATEGORIES_ID]) ? $this->catsProdsCnt[$category->CATEGORIES_ID] : 0;?>)</li>
	<?php endforeach;?>
	</ul>
<?php endif;?>

<?php echo $this->render('catalog.phtml');?>
