<table id="list" class="scroll"></table>
<div id="pager" class="scroll" style="text-align:center;"></div>
<div id="fieldsDialog" title="Category Error">
	<p>
		<span class="ui-icon ui-icon-circle-check" style="float:left; margin:0 7px 50px 0;"></span>
		Group not selected!<br />
		<b>Please select group for action!</b>
	</p>
</div>

<script type="text/javascript">
jQuery('#list').jqGrid({
	url:'/catalog/fieldgroups/list/format/json',
	datatype: 'json',
	mtype: 'GET',
	colNames:['Id', 'Alias', 'Title'],
	colModel :[
	  {name:'FIELDGROUPS_ID', index:'FIELDGROUPS_ID', sorttype:'int', width:'50'},
	  {name:'FIELDGROUPS_ALIAS', index:'FIELDGROUPS_ALIAS', width:'350', editable:true, editrules:{required:true}},
	  {name:'FIELDGROUPS_TITLE', index:'FIELDGROUPS_TITLE', width:'350', editable:true, editrules:{required:true}}],
	pager: jQuery('#pager'),
	rowNum:20,
	rowList:[20, 40, 60, 80, 100, 150, 200],
	sortname: 'FIELDGROUPS_ID',
	sortorder: 'asc',
	viewrecords: true,
	caption: 'Catalog Field Groups View',
	editurl: '/catalog/fieldgroups/edit',
	height:'auto',
	width:'auto'
}).navGrid('#pager',{
	edit:true, add:true, del:true, search:true
});

$("#fieldsDialog").dialog({
	bgiframe: true,
	modal: true,
	autoOpen: false,
	buttons: {
		Ok: function() {
			$(this).dialog('close');
		}
	}
});

</script>
