<div id="comments">
<?php echo $this->form ?>
<?php if (!empty($this->comments)):?>
	<ul id="commentsData">
	<?php foreach ($this->comments as $comment):?>
		<li class="bb">
			<dl>
				<dt><em class="bigger strong high"><?php echo $comment['POST_AUTHOR']?></em>&nbsp;|&nbsp;<em class="nonhigh"><?php echo $comment['POST_POSTDATE']?></em></dt>
				<dd><?php echo $comment['POST_POST']?></dd>
			</dl>
		</li>
	<?php endforeach;?>
	</ul>
<?php endif;?>
</div>
<script type="text/javascript">
	$("input:submit, input:button, button").button();
	$("#commentForm").submit(function() {
		var cont = $("#comments").parent();
		$.post(
			$(this).attr("action"),
			$(this).serialize(),
			function(data) {
				$.get(
					'/catalog/products/comments/product/<?php echo $this->product->getAlias();?>/format/html',
					function(data) {
						$("#comments").slideUp('slow', function() {
							$("#comments").detach();
						});
						cont.html(data);
						$("#comments").slideDown('slow');
					}
				);
			}
		);
		cont.html('Добавление коментария...');
		return false;
	});

</script>
