<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <meta http-equiv="content-language" content="en" />
  <meta name="robots" content="index,follow,noodp,noydir" />

  <meta name="author" lang="en" content="All: SatDevice [www.satdevice.com];" />
  <meta name="copyright" lang="en" content="KiT Studio" />

  <meta name="description" content="<?php echo implode(', ', (array)$this->description);?>" />
  <meta name="keywords" content="SatDevice<?php if (!empty($this->keywords)) echo ',' . implode(',', array_unique($this->keywords));?>" />

  <?php echo $this->headLink();?>
  <link rel="stylesheet" media="screen,projection" type="text/css" href="/css/main.css" />
  <!--[if lte IE 6]><link rel="stylesheet" type="text/css" href="/css/main-msie.css" /><![endif]-->
  <link rel="stylesheet" media="screen,projection" type="text/css" href="/css/scheme.css" />
  <link rel="stylesheet" media="print" type="text/css" href="/css/print.css" />

  <script type="text/javascript" src="/js/jquery/jquery-1.4.2.min.js"></script>
  <script type="text/javascript" src="/js/jquery/jquery.cookie.min.js"></script>
  <?php echo $this->headScript();?>
  <script type="text/javascript" src="/js/custom.js"></script>
  <?php echo $this->headTitle();?>
</head>

<body>

<div id="main">
  <!-- Header -->
  <div id="header" class="box">
      <div>
          <a href="/" title="SatDevice - Все для спутникового телевидения"><img style="float:left;margin:0 15px 0 0;" src="/images/logo781.gif" alt="SatDevice - Все для спутникового телевидения" /></a>
          <h1 id="logo"><a href="/" title="SatDevice - Все для спутникового телевидения">SatDevice</a></h1>
          <p id="slogan">Все для спутникового телевидения</p>
      </div>
      <hr class="noscreen" />
      <!-- Search -->
      <div id="search">
          <form action="" method="get">
              <div>
                  <span class="noscreen">Поиск:</span>
                  <input type="text" size="30" name="query" id="search-input" />
                  <input type="submit" value="Search" id="search-submit" />
              </div>
          </form>
      </div> <!-- /search -->
  </div> <!-- /header -->

  <hr class="noscreen" />

  <!-- Navigation -->
  <div id="nav" class="box">
      <h3 class="noscreen">Разделы</h3>
      <ul>
          <li <?php if (!$this->activeCategory):?>id="nav-active"<?php endif;?>><a href="/">Главная</a></li>
      <?php foreach ($this->categories as $categoryAlias => $categoryTitle):?>
          <li <?php if ($this->activeCategory == $categoryAlias):?>id="nav-active"<?php endif;?>><a href="<?php echo $this->url(array('module' => 'catalog', 'controller' => 'categories', 'action' => 'list'), null, true); ?>/category/<?php echo $categoryAlias;?>"><?php echo $categoryTitle; ?></a></li>
      <?php endforeach;?>
          <li><a href="/contacts">Контакты</a></li>
      </ul>
  </div> <!-- /nav -->

  <hr class="noscreen" />

  <h4 class="hx-style01"><span>Предложения партнеров</span></h4>
  <div class="box h-ads">
      <a href="#"><img src="/images/image-02.gif" alt="" class="nom" /></a>
      <a href="#"><img src="/images/image-02.gif" alt="" /></a>
      <a href="#"><img src="/images/image-02.gif" alt="" /></a>
      <a href="#"><img src="/images/image-02.gif" alt="" /></a>
      <a href="#"><img src="/images/image-02.gif" alt="" /></a>
      <a href="#"><img src="/images/image-02.gif" alt="" /></a>
  </div>

  <hr class="noscreen" />

  <!-- Main content -->
  <div id="content" class="box">
    <?php echo $this->layout()->content ?>
  </div> <!-- /content -->

  <hr class="noscreen" />
  <h4 class="hx-style01"><span>Предложения партнеров</span></h4>
  <div class="box h-ads">
      <a href="#"><img src="/images/image-02.gif" alt="" class="nom" /></a>
      <a href="#"><img src="/images/image-02.gif" alt="" /></a>
      <a href="#"><img src="/images/image-02.gif" alt="" /></a>
      <a href="#"><img src="/images/image-02.gif" alt="" /></a>
      <a href="#"><img src="/images/image-02.gif" alt="" /></a>
      <a href="#"><img src="/images/image-02.gif" alt="" /></a>
  </div>

  <hr class="noscreen" />

  <!-- Footer -->
  <div id="footer">
      <div class="f-left" style="margin:0 5px 0 0;">
      <!--LiveInternet counter--><script type="text/javascript"><!--
      document.write("<a href='http://www.liveinternet.ru/click' rel='nofollow'"+
      "target=_blank><img src='//counter.yadro.ru/hit?t27.7;r"+
      escape(document.referrer)+((typeof(screen)=="undefined")?"":
      ";s"+screen.width+"*"+screen.height+"*"+(screen.colorDepth?
      screen.colorDepth:screen.pixelDepth))+";u"+escape(document.URL)+
      ";"+Math.random()+
      "' alt='' title='LiveInternet: показано количество просмотров и"+
      " посетителей' "+
      "border='0' width='88' height='120'><\/a>")
      //--></script><!--/LiveInternet-->
      </div>
      <div>
          <noindex><p class="robots-nocontent"><a href="http://www.nuviotemplates.com/" rel="nofollow">Free web templates</a> presented by <a href="http://www.qartin.cz/" rel="nofollow">QARTIN</a>, vacation <a href="http://www.puntacana.net/" rel="nofollow">Punta Cana</a></p></noindex>
          <p>&copy;&nbsp;2010 <a href="/">SatDevice.com</a></p>
          <p id="support">Поддержка сайта: <a href=""></a></p>
      </div>
  </div> <!-- /footer -->
</div> <!-- /main -->
</body>
</html>
