-- 24-10-2009
CREATE TABLE `MIXMART_ADVERTIZERS` (
  `ADVERTIZERS_ID` int(10) unsigned NOT NULL,
  `ADVERTIZERS_TITLE` char(120) NOT NULL default '',
  PRIMARY KEY  (`ADVERTIZERS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MIXMART_REGIONSDELIVERY` (
  `REGIONSDELIVERY_ID` int(10) unsigned NOT NULL,
  `REGIONSDELIVERY_TITLE` char(120) NOT NULL default '',
  PRIMARY KEY  (`REGIONSDELIVERY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MIXMARKET_ADVREGIONDELIVERY` (
  `ADVREGIONDELIVERY_ADVID` int(10) unsigned NOT NULL,
  `ADVREGIONDELIVERY_RDID` int(10) unsigned NOT NULL,
  UNIQUE KEY `ADVID_RDID` (`ADVREGIONDELIVERY_ADVID`,`ADVREGIONDELIVERY_RDID`),
  CONSTRAINT `MIXMARKET_ADVREGIONDELIVERY_ibfk_1` FOREIGN KEY (`ADVREGIONDELIVERY_ADVID`) REFERENCES `MIXMART_ADVERTIZERS` (`ADVERTIZERS_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `MIXMARKET_ADVREGIONDELIVERY_ibfk_2` FOREIGN KEY (`ADVREGIONDELIVERY_RDID`) REFERENCES `MIXMART_REGIONSDELIVERY` (`REGIONSDELIVERY_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MIXMARKET_REGIONSGEOTAGRET` (
  `REGIONSGEOTAGRET_ID` int(10) unsigned NOT NULL,
  `REGIONSGEOTAGRET_PID` int(10) unsigned NOT NULL,
  `REGIONSGEOTAGRET_TITLE` char(120) NOT NULL default '',
  PRIMARY KEY  (`REGIONSGEOTAGRET_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MIXMARKET_ADVREGIONGEOTARGET` (
  `ADVREGIONGEOTARGET_ADVID` int(10) unsigned NOT NULL,
  `ADVREGIONGEOTARGET_RGTID` int(10) unsigned NOT NULL,
  UNIQUE KEY `ADVID_RGTID` (`ADVREGIONGEOTARGET_ADVID`,`ADVREGIONGEOTARGET_RGTID`),
  KEY `MIXMARKET_ADVREGIONGEOTARGET_ibfk_2` (`ADVREGIONGEOTARGET_RGTID`),
  CONSTRAINT `MIXMARKET_ADVREGIONGEOTARGET_ibfk_1` FOREIGN KEY (`ADVREGIONGEOTARGET_ADVID`) REFERENCES `MIXMART_ADVERTIZERS` (`ADVERTIZERS_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `MIXMARKET_ADVREGIONGEOTARGET_ibfk_2` FOREIGN KEY (`ADVREGIONGEOTARGET_RGTID`) REFERENCES `MIXMARKET_REGIONSGEOTAGRET` (`REGIONSGEOTAGRET_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MIXMARKET_CURRENCIES` (
  `CURRENCIES_ID` char(8) NOT NULL default '',
  `CURRENCIES_RATE` float(5,2) default '0.00',
  `CURRENCIES_TITLE` char(8) NOT NULL default '',
  PRIMARY KEY  (`CURRENCIES_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MIXMARKET_BRANDS` (
  `BRANDS_ID` int(10) unsigned NOT NULL,
  `BRANDS_TITLE` char(120) NOT NULL default '',
  PRIMARY KEY  (`BRANDS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MIXMARKET_CATEGORIES` (
  `CATEGORIES_ID` int(10) unsigned NOT NULL,
  `CATEGORIES_PID` int(10) unsigned NOT NULL default '0',
  `CATEGORIES_TITLE` char(80) NOT NULL default '',
  PRIMARY KEY  (`CATEGORIES_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MIXMARKET_OFFERS` (
  `OFFERS_ID` int(10) unsigned NOT NULL,
  `OFFERS_BRANDID` int(10) unsigned NOT NULL,
  `OFFERS_ADVID` int(10) unsigned NOT NULL,
  `OFFERS_CATID` int(10) unsigned NOT NULL,
  `OFFERS_IMG` text(500) default '',
  `OFFERS_IMGW` smallint(5) unsigned default '0',
  `OFFERS_IMGH` smallint(5) unsigned default '0',
  `OFFERS_TYPE` char(120) default '',
  `OFFERS_NAME` char(120) NOT NULL default '',
  `OFFERS_URL` text NOT NULL default '',
  `OFFERS_CURRENCYID` char(8) NOT NULL default '',
  `OFFERS_DESC` text default '',
  `OFFERS_PRICE` float(9,2) NOT NULL default '0.00',
  PRIMARY KEY  (`OFFERS_ID`),
  KEY `OFFERS_BRANDID` (`OFFERS_BRANDID`),
  KEY `OFFERS_ADVID` (`OFFERS_ADVID`),
  KEY `OFFERS_CATID` (`OFFERS_CATID`),
  KEY `OFFERS_CURRENCYID` (`OFFERS_CURRENCYID`),
  CONSTRAINT `MIXMARKET_OFFERS_ibfk_1` FOREIGN KEY (`OFFERS_BRANDID`) REFERENCES `MIXMARKET_BRANDS` (`BRANDS_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `MIXMARKET_OFFERS_ibfk_2` FOREIGN KEY (`OFFERS_ADVID`) REFERENCES `MIXMART_ADVERTIZERS` (`ADVERTIZERS_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `MIXMARKET_OFFERS_ibfk_3` FOREIGN KEY (`OFFERS_CATID`) REFERENCES `MIXMARKET_CATEGORIES` (`CATEGORIES_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `MIXMARKET_OFFERS_ibfk_4` FOREIGN KEY (`OFFERS_CURRENCYID`) REFERENCES `MIXMARKET_CURRENCIES` (`CURRENCIES_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

