<table id="list" class="scroll"></table>
<div id="pager" class="scroll" style="text-align:center;"></div>

<script type="text/javascript">
jQuery('#list').jqGrid({
	url:'/catalog/fields/list/format/json',
	datatype: 'json',
	mtype: 'GET',
	colNames:['Id', 'Alias', 'Title', 'Field Type'],
	colModel :[
	  {name:'FIELDS_ID', index:'FIELDS_ID', sorttype:'int', width:50},
	  {name:'FIELDS_ALIAS', index:'FIELDS_ALIAS', editable:true, editrules:{required:true}},
	  {name:'FIELDS_TITLE', index:'FIELDS_TITLE', editable:true, editrules:{required:true}},
	  {name:'SFIELDS_FIELDTYPE', index:'SFIELDS_FIELDTYPE', edittype:'select', editable:true, editrules:{required:true}, editoptions:{value:{<?php foreach ($this->fieldTypes as $id => $title) echo "{$id}:'{$title}',"; ?>}}}],
	pager: jQuery('#pager'),
	rowNum:20,
	rowList:[20, 40, 60, 80, 100, 150, 200],
	sortname: 'FIELDS_ID',
	sortorder: 'asc',
	viewrecords: true,
	caption: 'Brands View',
	editurl: '/catalog/fields/edit',
	height:'auto',
	width:'auto'
}).navGrid('#pager',{
	edit:true, add:true, del:true, search:true
});
</script>
